# Generated by Django 2.0.4 on 2018-04-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180408_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ProjectStatus', verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProjectType', verbose_name='type'),
        ),
    ]
