# Generated by Django 2.0.4 on 2018-04-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180408_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://google.com', max_length=300, verbose_name='url'),
            preserve_default=False,
        ),
    ]
