# Generated by Django 2.0.4 on 2018-04-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='entitytype',
            options={'verbose_name': 'entity type', 'verbose_name_plural': 'entity types'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectevent',
            options={'verbose_name': 'project event', 'verbose_name_plural': 'project events'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name': 'project status', 'verbose_name_plural': 'project status'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name': 'project type', 'verbose_name_plural': 'project types'},
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
